# Generated by Django 3.2.16 on 2022-10-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20221011_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1992-02-21'),
            preserve_default=False,
        ),
    ]
